disabled_rules: # rule identifiers to exclude from running
  - identifier_name
  - function_parameter_count
  - trailing_whitespace
  - line_length

excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Pods
